version: 2
#unique, not_null_relationship_accep_values , alguns tipos de teste
sources:
  - name: sap_adw
    database: dbt-project-1-431420
    schema: sap_adw
    tables:

      - name: address
        description: Address information for customers, employees, and vendors
        columns:
          - name: addressid
            description: Primary key of the address table
            data_tests:
              - unique
              - not_null
          - name: city
            description: City of the address
            data_tests:
              - not_null
          - name: stateprovinceid
            description: Foreign key to the state province table
            data_tests:
              - not_null
              - relationships:
                  to: ref('stateprovince')
                  field: stateprovinceid

      - name: countryregion
        description: Country and region information
        columns:
          - name: countryregioncode
            description: Primary key for countryregion
            data_tests:
              - unique
              - not_null
          - name: name
            description: Country or region name
            data_tests:
              - not_null

      - name: customer
        description: Current customer information
        columns:
          - name: customerid
            description: Primary key for customer records
            data_tests:
              - unique
              - not_null
          - name: territoryid
            description: ID of the territory in which the customer is located
            data_tests:
              - not_null
              - relationships:
                  to: ref('sales_territory')
                  field: territoryid

      - name: person
        description: Individual customers, contacts, and venders
        columns:
          - name: businessentityid
            description: Primary key for person records
            data_tests:
              - unique
              - not_null
          - name: person_type
            description: Type of person
            data_tests:
              - not_null
          - name: firstname
            description: First name of the person
            data_tests:
              - not_null
          - name: lastname
            description: Last name of the person
            data_tests:
              - not_null

      - name: product
        description: Products sold or used in the manufacture of sold products
        columns:
          - name: productid
            description: Primary key for product records
            data_tests:
              - unique
              - not_null
          - name: name
            description: Name of the product
            data_tests:
              - not_null
          - name: productnumber
            description: Unique product identification number
            data_tests:
              - not_null


 
